[package]
name = "tauri-plugin-codepush"
version = "0.1.0"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-codepush"

[dependencies]
serde = { workspace = true }
tauri = { workspace = true }
thiserror = { workspace = true }
tokio = "1.43.0"
semver = "1.0.25"

[build-dependencies]
tauri-plugin = { version = "2.0.3", features = ["build"] }
